### ISSUE TITLE
Removing Values

### ISSUE THREAD

**Issue by EthanBautista** [707Alex707/Sudoku#4]
For removing values, is it better to hide the display property of a cell or changing the input of the cell to a blank? Removing values also does not create unique solutions.

**Comment by 707Alex707** [comment]
For removing values, I think its better to remove the value, because it makes it easier pull what the user has inserted into the table (if that gets implemented) . Also setting the visibility breaks storeToArray() function. Not that its used at this current time. differentiate between what the user

Testing that there is not multiple solutions, I think this beyond the scope of this project
